#!/bin/sh
# shellcheck disable=SC1091

set -eu

script_path=$(readlink -f "$0" 2>/dev/null || printf '%s' "$0")

case "$script_path" in
    */*) lib_dir=${script_path%/*} ;;
    *) lib_dir=. ;;
esac

. "$lib_dir/lib/runtime-contract.sh"

runtime_entrypoint_main "$@"
